In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
netflix=pd.read_csv(r"C:\Users\HP\Downloads\archive\netflix_titles.csv")
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [3]:
# How many rows and columns are present in the dataset?
netflix.shape

(8807, 12)

In [4]:
# What are the column names in the dataset?
netflix.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [5]:
# What are the data types of each column?
netflix.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [6]:
# Are there any missing values in the dataset?
netflix.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [7]:
# Which columns contain the highest number of null values?
netflix.isnull().sum().sort_values(ascending=False).head(1)

director    2634
dtype: int64

In [8]:
# Are there any duplicate records in the dataset?
netflix.duplicated().sum()

np.int64(0)

In [9]:
# Content Analysis

In [10]:
# How many Movies and TV Shows are present on Netflix?
netflix.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [11]:
netflix["type"].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [12]:
# Which type of content is more common: Movies or TV Shows?
netflix["type"].value_counts().head(1)

type
Movie    6131
Name: count, dtype: int64

In [16]:
# What is the most common rating on Netflix?
netflix["rating"].head(1)

0    PG-13
Name: rating, dtype: object

In [17]:
# Which movie rating appears the most?
netflix[netflix["type"]=="Movie"]["rating"].value_counts().head(1)

rating
TV-MA    2062
Name: count, dtype: int64

In [18]:
# Which TV Show rating appears the most?
netflix[netflix["type"]=="TV Show"]["rating"].value_counts().head(1)

rating
TV-MA    1145
Name: count, dtype: int64

In [19]:
# Which country has produced the highest amount of Netflix content?
netflix["country"].value_counts().head(1)

country
United States    2818
Name: count, dtype: int64

In [20]:
# What are the top 10 countries producing Netflix content?
netflix["country"].value_counts().head(10)

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
Name: count, dtype: int64

In [21]:
# How much content is produced by India?
netflix[netflix["country"] == "India"]["type"].value_counts()

type
Movie      893
TV Show     79
Name: count, dtype: int64

In [22]:
# How much content is produced by the United States?
netflix[netflix["country"]=="United States"]["type"].value_counts()

type
Movie      2058
TV Show     760
Name: count, dtype: int64

In [23]:
# Release Year Analysis

In [24]:
# Which year had the highest number of releases?
netflix.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [25]:
netflix[ 'release_year'].value_counts().head(1)

release_year
2018    1147
Name: count, dtype: int64

In [26]:
# How many titles were released after 2020?
netflix[netflix["release_year"]>2020]["title"].count()

np.int64(592)

In [27]:
# How many titles were released before 2000?
netflix[netflix["release_year"]<2000]["title"].count()

np.int64(525)

In [28]:
# What is the oldest movie/show available in the dataset?
netflix["release_year"].min()

1925

In [ ]:
# Genre Analysis

In [32]:
# Which genre is most common on Netflix?
netflix["listed_in"].value_counts().head(1)

listed_in
Dramas, International Movies    362
Name: count, dtype: int64

In [33]:
# What are the top 10 genres?
netflix["listed_in"].value_counts().head(10)

listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
Kids' TV                                            220
Children & Family Movies                            215
Children & Family Movies, Comedies                  201
Documentaries, International Movies                 186
Dramas, International Movies, Romantic Movies       180
Name: count, dtype: int64

In [35]:
# Which genre has the least content?
netflix["listed_in"].value_counts().tail()

listed_in
Action & Adventure, Cult Movies                     1
Action & Adventure, Comedies, Music & Musicals      1
Classic Movies, Horror Movies, Thrillers            1
Children & Family Movies, Classic Movies, Dramas    1
Cult Movies, Dramas, Thrillers                      1
Name: count, dtype: int64

In [41]:
# How many Comedy movies are present?
netflix.columns
netflix[netflix["listed_in"].str.contains("Comedy")].shape[0]

399

In [42]:
# How many Drama shows are present?
netflix[netflix["listed_in"].str.contains("Drama")].shape[0]

3190

In [ ]:
# Duration Analysis

In [45]:
# What is the longest movie on Netflix?
netflix.columns
netflix["duration"].value_counts().head(1)

duration
1 Season    1793
Name: count, dtype: int64

In [46]:
# What is the shortest movie on Netflix?
netflix["duration"].value_counts().tail(1)

duration
191 min    1
Name: count, dtype: int64

In [57]:
# Which TV Show has the highest number of seasons?
tv = netflix[netflix["type"] == "TV Show"]

tv["duration"] = tv["duration"].str.replace(" Seasons", "").str.replace(" Season", "").astype(int)

tv.sort_values(by="duration", ascending=False)[["title", "duration"]].head(1)

C:\Users\HP\AppData\Local\Temp\ipykernel_25704\3310111731.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tv["duration"] = tv["duration"].str.replace(" Seasons", "").str.replace(" Season", "").astype(int)

              title  duration
548  Grey's Anatomy        17

In [ ]:
# Director & Cast Analysis

In [59]:
# Which director has directed the most content on Netflix?
netflix["director"].value_counts().head()

director
Rajiv Chilaka             19
Raúl Campos, Jan Suter    18
Suhas Kadav               16
Marcus Raboy              16
Jay Karas                 14
Name: count, dtype: int64

In [63]:
# Which actor appears most frequently?
netflix.columns
netflix["cast"].dropna().str.split(",").explode().value_counts().head(1)

cast
Anupam Kher    43
Name: count, dtype: int64

In [67]:
# Which actors appear in the highest number of movies?
netflix[netflix["type"]=="Movie"]["cast"].str.split(", ").explode().value_counts().head(1)

cast
Anupam Kher    42
Name: count, dtype: int64

In [71]:
# Which directors worked on both Movies and TV Shows?
set(netflix[netflix["type"]=="Movie"]["director"].dropna()) & set(netflix[netflix["type"]=="TV Show"]["director"].dropna())

{'Alessandro Angulo',
 'BB Sasore',
 'Billy Corben',
 'Brad Anderson',
 'Bunmi Ajakaiye',
 'Cosima Spender',
 'Dan Forrer',
 'Daniel Kontur',
 'David Ayer',
 'Eli Roth',
 'Estela Renner',
 'Jalil Lespert',
 'Jay Chandrasekhar',
 'Jerry Seinfeld',
 'Joe Berlinger',
 'John Dower',
 'Julien Leclercq',
 'Justin Webster',
 'Kemi Adetiba',
 'Kim Seong-hun',
 'Kobun Shizuno, Hiroyuki Seshita',
 'Kyran Kelly',
 'Malik Nejer',
 'Manolo Caro',
 'Marcus Raboy',
 'Mark Tonderai',
 'Masaaki Yuasa',
 'Mateo Gil',
 'Michael Simon',
 'Mike Flanagan',
 'Noam Murro',
 'Obi Emelonye',
 'Oliver Stone',
 'Olivier Megaton',
 'Oriol Paulo',
 'Quentin Tarantino',
 'Ryan Polito',
 'Sion Sono',
 'Soumendra Padhi',
 'Stan Lathan',
 'Steven Bognar, Julia Reichert',
 'Tensai Okamura',
 'Thierry Demaizière, Alban Teurlai',
 'Thomas Astruc',
 'Tiller Russell',
 'Tosin Coker',
 'Tsutomu Mizushima',
 'Ziad Doueiri'}

In [ ]:
# Date Added Analysis

In [76]:
# Which year had the highest Netflix additions?
netflix.columns
netflix["date_added"] = pd.to_datetime(netflix["date_added"].str.strip(), errors="coerce")
netflix["date_added"].dt.year.value_counts().head(1)

# errors="coerce"
# converts bad values to NaT (missing datetime)
# prevents crash

date_added
2019.0    2016
Name: count, dtype: int64